services:
  - type: web
    name: disaster-response-fastapi
    plan: free
    runtime: python
    repo: https://github.com/Gokulkiran418/disaster-management-chatbot.git
    branch: main
    buildCommand: "pip install -r api/requirements.txt"
    startCommand: "gunicorn api.index:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
  - type: web
    name: disaster-response-frontend
    plan: free
    runtime: node
    repo: https://github.com/your-username/your-repo
    branch: main
    buildCommand: "cd src && npm install && npm run build"
    startCommand: "cd src && npm start"